// demo/svelte/src/lib/node_ui/Connector.svelte
<script lang="ts">
  import {
    NodeComponent,
    ConnectorComponent,
    Engine,
  } from "../../../../../src/index";
  import { getContext, onDestroy } from "svelte";

  let {
    name,
    maxConnectors = 1,
    allowDragOut = true,
  }: {
    name: string;
    maxConnectors?: number;
    allowDragOut?: boolean;
  } = $props();

  let engine: Engine = getContext("engine");
  let nodeObject: NodeComponent = getContext("nodeObject");
  let connector = new ConnectorComponent(engine.global, nodeObject, {
    name: name,
    maxConnectors: maxConnectors,
    allowDragOut: allowDragOut,
  });

  nodeObject.addConnectorObject(connector);

  export function object(): ConnectorComponent {
    return connector;
  }

  onDestroy(() => {
    connector.destroy();
  });
</script>

<div class="connector" bind:this={connector.element}></div>

<style>
</style>

// demo/react/src/lib/node_ui/Connector.tsx
import {
  useContext,
  useEffect,
  useRef,
  forwardRef,
  useImperativeHandle,
  createContext,
} from "react";
import { NodeComponent, ConnectorComponent } from "../../../../../src/index";
import { EngineContext } from "../Canvas";

// Create context for NodeObject - will be provided by Node component
export const NodeObjectContext = createContext<NodeComponent | null>(null);

interface ConnectorProps {
  name: string;
  maxConnectors?: number;
  allowDragOut?: boolean;
}

export interface ConnectorRef {
  object(): ConnectorComponent;
}

const ConnectorReact = forwardRef<ConnectorRef, ConnectorProps>(
  ({ name, maxConnectors = 1, allowDragOut = true }, ref) => {
    const engine = useContext(EngineContext);
    const nodeObject = useContext(NodeObjectContext);
    const connectorRef = useRef<ConnectorComponent | null>(null);
    const elementRef = useRef<HTMLDivElement>(null);

    useImperativeHandle(ref, () => ({
      object: () => connectorRef.current!,
    }));

    useEffect(() => {
      if (!engine || !nodeObject) {
        console.warn("Connector: Missing engine or nodeObject in context");
        return;
      }

      connectorRef.current = new ConnectorComponent(engine.global, nodeObject, {
        name: name,
        maxConnectors: maxConnectors,
        allowDragOut: allowDragOut,
      });

      nodeObject.addConnectorObject(connectorRef.current);

      if (elementRef.current) {
        connectorRef.current.element = elementRef.current;
      }

      return () => {
        if (connectorRef.current) {
          connectorRef.current.destroy();
        }
      };
    }, [engine, nodeObject, name, maxConnectors, allowDragOut]);

    return <div className="connector" ref={elementRef}></div>;
  },
);

ConnectorReact.displayName = "ConnectorReact";

export default ConnectorReact;
