// assets/snapline/svelte/src/Line.svelte
<script lang="ts">
    import type { LineComponent } from "@snap-engine/snapline";
    import { onMount } from "svelte";
    let { line }: { line: LineComponent } = $props();

    let style = $state("position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(0px, 0px, 0);");
    let dx = $state(0);
    let dy = $state(0);
    let x0 = $state(line.worldTransform.x);
    let y0 = $state(line.worldTransform.y);
    let x1 = $state(0);
    let y1 = $state(0);
    let x2 = $state(0);
    let y2 = $state(0);
    let x3 = $state(0);
    let y3 = $state(0);

    function renderLine() {
      const thisLine: LineComponent = line;
      x0 = thisLine.worldTransform.x;
      y0 = thisLine.worldTransform.y;
      style = `position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(${x0}px, ${y0}px, 0);`;
      dx = thisLine.endWorldX - thisLine.worldTransform.x;
      dy = thisLine.endWorldY - thisLine.worldTransform.y;
        x1 = Math.abs(dx / 2);
        y1 = 0;
        x2 = dx - Math.abs(dx / 2);
        y2 = dy;
        x3 = dx;
        y3 = dy;
    }

    let lineDOM: SVGElement | null = null;

  onMount(() => {
    line.element = (lineDOM as unknown as HTMLElement);
    line.callback.afterWrite2 = renderLine;
  });
</script>

<svg
  data-snapline-type="connector-line"
  width="4"
  height="4"
  style={style}
  bind:this={lineDOM}
>
  <path
    class="sl-connector-line"
    d={`M 0,0 C ${x1}, ${y1} ${x2}, ${y2} ${x3}, ${y3}`}
    marker-end="url(#arrow)"
  />
  <marker id="arrow" viewBox="0 0 24 24" refX="0" refY="12" orient="auto">
    <polygon points="4,4 20,12 4,22" fill="#545454"/>
  </marker>
</svg>

<style>
  svg {
    z-index: 1000;
  }
  path {
    fill: none;
    stroke: #545454;
    stroke-width: 4;
    stroke-linecap: round;
    stroke-linejoin: round;
  }
</style>

// demo/react/src/lib/node_ui/Line.tsx
import { useEffect, useRef, useState } from "react";
import type { LineComponent } from "../../../../../src/index";

interface LineProps {
  line: LineComponent;
}

export default function LineReact({ line }: LineProps) {
  const lineDOM = useRef<SVGSVGElement>(null);
  const [style, setStyle] = useState(
    "position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(0px, 0px, 0);",
  );
  const [, setDx] = useState(0);
  const [, setDy] = useState(0);
  const [, setX0] = useState(line.worldTransform.x);
  const [, setY0] = useState(line.worldTransform.y);
  const [x1, setX1] = useState(0);
  const [y1, setY1] = useState(0);
  const [x2, setX2] = useState(0);
  const [y2, setY2] = useState(0);
  const [x3, setX3] = useState(0);
  const [y3, setY3] = useState(0);

  const renderLine = () => {
    const thisLine: LineComponent = line;
    const newX0 = thisLine.worldTransform.x;
    const newY0 = thisLine.worldTransform.y;
    setX0(newX0);
    setY0(newY0);
    setStyle(
      `position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(${newX0}px, ${newY0}px, 0);`,
    );
    const newDx = thisLine.endWorldX - thisLine.worldTransform.x;
    const newDy = thisLine.endWorldY - thisLine.worldTransform.y;
    setDx(newDx);
    setDy(newDy);
    setX1(Math.abs(newDx / 2));
    setY1(0);
    setX2(newDx - Math.abs(newDx / 2));
    setY2(newDy);
    setX3(newDx);
    setY3(newDy);
  };

  useEffect(() => {
    if (lineDOM.current) {
      line.element = lineDOM.current as unknown as HTMLElement;
      line.callback.afterWrite2 = renderLine;
    }
  }, [line]);

  return (
    <svg
      data-snapline-type="connector-line"
      width="4"
      height="4"
      style={{ ...parseStyle(style), zIndex: 1000 }}
      ref={lineDOM}
    >
      <path
        className="sl-connector-line"
        d={`M 0,0 C ${x1}, ${y1} ${x2}, ${y2} ${x3}, ${y3}`}
        markerEnd="url(#arrow)"
        style={{
          fill: "none",
          stroke: "#545454",
          strokeWidth: 4,
          strokeLinecap: "round",
          strokeLinejoin: "round",
        }}
      />
      <marker id="arrow" viewBox="0 0 24 24" refX="0" refY="12" orient="auto">
        <polygon points="4,4 20,12 4,22" fill="#545454" />
      </marker>
    </svg>
  );
}

// Helper function to parse CSS string to object
function parseStyle(styleString: string): React.CSSProperties {
  const styles: React.CSSProperties = {};
  styleString.split(";").forEach((style) => {
    const [key, value] = style.split(":").map((s) => s.trim());
    if (key && value) {
      // Convert kebab-case to camelCase
      const camelKey = key.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
      styles[camelKey as keyof React.CSSProperties] = value as any;
    }
  });
  return styles;
}
