// assets/snapline/svelte/src/Connector.svelte
<script lang="ts">
  import {
    NodeComponent,
    ConnectorComponent,
  } from "@snap-engine/snapline";
  import type { Engine } from "@snap-engine/core";
  import { getContext, onDestroy, onMount } from "svelte";

  let {
    name,
    maxConnectors = 1,
    allowDragOut = true,
  }: {
    name: string;
    maxConnectors?: number;
    allowDragOut?: boolean;
  } = $props();

  let engine: Engine = getContext("engine");
  let nodeObject: NodeComponent = getContext("nodeObject");
  let connector = new ConnectorComponent(engine, nodeObject, {
    name: name,
    maxConnectors: maxConnectors,
    allowDragOut: allowDragOut,
  });

  nodeObject.addConnectorObject(connector);
  let connectorDOM: HTMLDivElement | null = null;

  export function object(): ConnectorComponent {
    return connector;
  }

  onMount(() => {
    connector.element = connectorDOM as HTMLElement;
  });

  onDestroy(() => {
    connector.destroy();
  });
</script>

<div
  bind:this={connectorDOM}
  data-snapline-type="connector"
  data-snapline-name={name}
  class={`connector ${allowDragOut ? "right" : "left"}`}
></div>

<style>
  .connector {
    width: 14px;
    height: 14px;
    border: 2px solid #ffffff;
    border-radius: 999px;
    background: #4f46e5;
    box-shadow: 0 1px 3px rgba(15, 23, 42, 0.25);
    cursor: crosshair;
    pointer-events: auto;
  }
</style>

// assets/snapline/react/src/Connector.tsx
import {
  forwardRef,
  useContext,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
} from "react";
import { ConnectorComponent } from "@snap-engine/snapline";
import { useSnapLineEngine } from "./Engine";
import { NodeObjectContext } from "./Node";

export interface ConnectorProps {
  allowDragOut?: boolean;
  className?: string;
  maxConnectors?: number;
  name: string;
  style?: CSSProperties;
}

export interface ConnectorRef {
  object(): ConnectorComponent;
}

export const Connector = forwardRef<ConnectorRef, ConnectorProps>(
  (
    {
      allowDragOut = true,
      className = "",
      maxConnectors = 1,
      name,
      style,
    },
    ref,
  ) => {
    const engine = useSnapLineEngine();
    const nodeObject = useContext(NodeObjectContext);
    if (!nodeObject) {
      throw new Error("<Connector> must be rendered inside <Node>.");
    }

    const connectorDomRef = useRef<HTMLDivElement>(null);
    const connectorRef = useRef<ConnectorComponent | null>(null);
    if (!connectorRef.current) {
      connectorRef.current = new ConnectorComponent(engine, nodeObject, {
        allowDragOut,
        maxConnectors,
        name,
      });
      nodeObject.addConnectorObject(connectorRef.current);
    }
    const connector = connectorRef.current;

    useImperativeHandle(ref, () => ({
      object: () => connector,
    }));

    useEffect(() => {
      if (connectorDomRef.current) {
        connector.element = connectorDomRef.current;
      }
      return () => {
        connector.destroy();
      };
    }, [connector]);

    return (
      <div
        ref={connectorDomRef}
        data-snapline-name={name}
        data-snapline-type="connector"
        className={`connector ${allowDragOut ? "right" : "left"} ${className}`.trim()}
        style={{
          background: "#4f46e5",
          border: "2px solid #ffffff",
          borderRadius: 999,
          boxShadow: "0 1px 3px rgba(15, 23, 42, 0.25)",
          cursor: "crosshair",
          height: 14,
          pointerEvents: "auto",
          width: 14,
          ...style,
        }}
      />
    );
  },
);
