// assets/asset-base/svelte/src/Engine.svelte
<script lang="ts">
  import { onDestroy, onMount, setContext, type Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { Engine as CoreEngine } from "@snap-engine/core";
  import { DebugRenderer } from "@snap-engine/core/debug";
  import { CollisionEngine } from "@snap-engine/core/collision";

  type EngineProps = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children: Snippet;
    className?: string;
    engine?: CoreEngine | null;
    debug?: boolean;
  };

  let {
    children,
    class: classValue = "",
    className = "",
    debug = false,
    engine = $bindable<CoreEngine | null>(null),
    id = "snap-canvas",
    style = "",
    ...divProps
  }: EngineProps = $props();

  const ownsEngine = typeof document !== "undefined" && engine == null;
  const resolvedEngine =
    typeof document === "undefined" ? null : (engine ?? new CoreEngine());
  engine = resolvedEngine;
  setContext("engine", resolvedEngine);

  if (resolvedEngine && !resolvedEngine.collisionEngine) {
    resolvedEngine.setCollisionEngine(new CollisionEngine());
  }

  let canvas: HTMLDivElement | null = null;
  let mounted = $state(false);
  let pendingDebugEnable = $state(false);
  const mergedClass = $derived(`${classValue} ${className}`.trim());
  const mergedStyle = $derived(
    `height:100%;overflow:visible;position:relative;${style ?? ""}`,
  );

  onMount(() => {
    if (!resolvedEngine || !canvas) return;
    resolvedEngine.assignDom(canvas);
    resolvedEngine.camera?.setCameraPosition(0, 0);
    mounted = true;

    if (pendingDebugEnable) {
      resolvedEngine.setDebugRenderer(new DebugRenderer());
      pendingDebugEnable = false;
    }
  });

  onDestroy(() => {
    if (!resolvedEngine) return;
    resolvedEngine.disableDebug();
    if (ownsEngine) {
      resolvedEngine.destroy();
    }
  });

  $effect(() => {
    if (!resolvedEngine) return;
    if (debug) {
      if (mounted) {
        resolvedEngine.setDebugRenderer(new DebugRenderer());
      } else {
        pendingDebugEnable = true;
      }
    } else {
      resolvedEngine.disableDebug();
      pendingDebugEnable = false;
    }
  });

  export function enableDebug() {
    if (!resolvedEngine) return;
    if (mounted) {
      resolvedEngine.setDebugRenderer(new DebugRenderer());
    } else {
      pendingDebugEnable = true;
    }
  }

  export function disableDebug() {
    if (!resolvedEngine) return;
    resolvedEngine.disableDebug();
    pendingDebugEnable = false;
  }
</script>

<div
  {...divProps}
  {id}
  class={mergedClass || undefined}
  bind:this={canvas}
  style={mergedStyle}
>
  {#if mounted}
    {@render children()}
  {/if}
</div>

// assets/snapline/react/src/Engine.tsx
import {
  createContext,
  useContext,
  useEffect,
  useRef,
  type CSSProperties,
  type ReactNode,
} from "react";
import { Engine as CoreEngine } from "@snap-engine/core";
import { CollisionEngine } from "@snap-engine/core/collision";
import { DebugRenderer } from "@snap-engine/core/debug";

export const EngineContext = createContext<CoreEngine | null>(null);

export function useSnapLineEngine(): CoreEngine {
  const engine = useContext(EngineContext);
  if (!engine) {
    throw new Error("SnapLine React components must be rendered inside <Engine>.");
  }
  return engine;
}

export interface EngineProps {
  children: ReactNode;
  className?: string;
  debug?: boolean;
  engine?: CoreEngine | null;
  id?: string;
  style?: CSSProperties;
}

export function SnapLineEngine({
  children,
  className,
  debug = false,
  engine = null,
  id = "snap-canvas",
  style,
}: EngineProps) {
  const ownedEngineRef = useRef<CoreEngine | null>(null);
  const canvasRef = useRef<HTMLDivElement>(null);

  if (!ownedEngineRef.current) {
    ownedEngineRef.current = engine ?? new CoreEngine();
  }
  const resolvedEngine = engine ?? ownedEngineRef.current;

  if (!resolvedEngine.collisionEngine) {
    resolvedEngine.setCollisionEngine(new CollisionEngine());
  }

  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }
    resolvedEngine.assignDom(canvasRef.current);
    resolvedEngine.camera?.setCameraPosition(0, 0);
  }, [resolvedEngine]);

  useEffect(() => {
    if (debug) {
      resolvedEngine.setDebugRenderer(new DebugRenderer());
    } else {
      resolvedEngine.disableDebug();
    }
  }, [debug, resolvedEngine]);

  return (
    <EngineContext.Provider value={resolvedEngine}>
      <div
        id={id}
        className={className}
        ref={canvasRef}
        style={{
          height: "100%",
          overflow: "hidden",
          position: "relative",
          ...style,
        }}
      >
        {children}
      </div>
    </EngineContext.Provider>
  );
}

export { SnapLineEngine as Engine };
