// demo/svelte/src/demo/node_ui_demo/Line.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { LineComponent } from "@snap-engine/snapline";
  import {blur} from "svelte/transition";

  let { line }: { line: LineComponent } = $props();

  let shadowOffset = 6;
  let style = $state(
    "position: absolute; overflow: visible; pointer-events: none; will-change: transform;"
  );
  let shadowStyle = $state(
    "position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(0px, 0px, 0);"
  );
  let endX = $state(0);
  let endY = $state(0);
  let path = $state("");

  let radius = 10;

  function renderLine() {
    // For now, assume the line starts heading to the right
    const thisLine: LineComponent = line;
    const x0 = thisLine.worldTransform.x;
    const y0 = thisLine.worldTransform.y;
    style = `position: absolute; overflow: visible; pointer-events: none; will-change: transform;`;
    shadowStyle = `position: absolute; overflow: visible; pointer-events: none; will-change: transform; transform: translate3d(${x0 + shadowOffset}px, ${y0 + shadowOffset}px, 0);`;
    const dx = thisLine.endWorldX - thisLine.worldTransform.x;
    const dy = thisLine.endWorldY - thisLine.worldTransform.y;
    const x1 = dx > 0 ? Math.abs(dx / 2) : radius;
    const x3 = dx;
    const y3 = dy;
    const arc_1 = `A ${radius} ${radius} 0 0 ${dy > 0 ? 1 : 0} ${x1} ${dy > 0 ? radius : -radius}`;
    const arc_2 = `A ${radius} ${radius} 0 0 ${dy > 0 ? (dx > 0 ? 0 : 1) : dx > 0 ? 1 : 0} ${x1 + (dx > 0 ? radius : -radius)} ${y3}`;
    path = `M 0,0 h ${x1 - radius} ${arc_1} v ${y3 - 2 * (dy > 0 ? radius : -radius)} ${arc_2} h ${dx > 0 ? x3 / 2 - radius : x3 - radius} `;
    endX = x3;
    endY = y3;
  }

  onMount(() => {
    renderLine();
    line.writeTransform();
    line.callback.afterWrite1 = renderLine;
    line.callback.afterWrite2 = renderLine;
  });
</script>

<svg
  data-snapline-type="connector-line"
  width="4"
  height="4"
  {style}
  bind:this={line.element as any}
  transition:blur|global={{ duration: 200 }}
>
  <defs>
    <linearGradient id="line-start-gradient" gradientTransform="rotate(0)">
      <stop offset="0%" stop-color="#c34421" />
      <stop offset="100%" stop-color="#F76E33" />
    </linearGradient>
    <linearGradient id="line-end-gradient" gradientTransform="rotate(0)">
      <stop offset="0%" stop-color="#F76E33" />
      <stop offset="100%" stop-color="#c34421" />
    </linearGradient>
  </defs>
  <path class="sl-connector-line" d={path} />
  <rect x={-1} y={-1} width={16} height={3} fill="url(#line-start-gradient)" />
  <rect
    x={endX - 16}
    y={endY - 1.5}
    width={16}
    height={3}
    fill="url(#line-end-gradient)"
  />
  <circle cx={0} cy={0} r="6" />
  <circle cx={endX} cy={endY} r="6" />
</svg>

<!-- <svg
  data-snapline-type="connector-line"
  width="4"
  height="4"
  style={shadowStyle}
  class="shadow"
>
  <path
    class="sl-connector-line shadow-line"
    d={path}
    marker-end="url(#arrow)"
  />
</svg> -->

<style>
  svg {
    z-index: 1000;
    pointer-events: none;
  }
  path {
    fill: none;
    stroke: #f76e33;
    stroke-width: 3;
    stroke-linecap: round;
    stroke-linejoin: round;
    border-radius: 10px;
  }
  circle {
    fill: #f76e33;
  }
  .shadow {
    z-index: 0;
  }
  .shadow-line {
    fill: none;
    stroke: #32333845;
    stroke-width: 4;
    stroke-linecap: round;
    filter: blur(5px);
  }
</style>

// assets/snapline/react/src/Line.tsx
import { useEffect, useRef, useState, type CSSProperties } from "react";
import type { LineComponent } from "@snap-engine/snapline";

export interface LineProps {
  line: LineComponent;
}

interface LineState {
  style: CSSProperties;
  x1: number;
  x2: number;
  x3: number;
  y1: number;
  y2: number;
  y3: number;
}

function getLineState(line: LineComponent): LineState {
  const dx = line.endWorldX - line.worldTransform.x;
  const dy = line.endWorldY - line.worldTransform.y;
  return {
    style: {
      overflow: "visible",
      pointerEvents: "none",
      position: "absolute",
      transform: `translate3d(${line.worldTransform.x}px, ${line.worldTransform.y}px, 0)`,
      willChange: "transform",
      zIndex: 1000,
    },
    x1: Math.abs(dx / 2),
    y1: 0,
    x2: dx - Math.abs(dx / 2),
    y2: dy,
    x3: dx,
    y3: dy,
  };
}

export function Line({ line }: LineProps) {
  const lineDomRef = useRef<SVGSVGElement>(null);
  const [lineState, setLineState] = useState<LineState>(() =>
    getLineState(line),
  );

  useEffect(() => {
    if (lineDomRef.current) {
      line.element = lineDomRef.current as unknown as HTMLElement;
    }
    const renderLine = () => {
      setLineState(getLineState(line));
    };
    const cleanup = line.onRender(renderLine);
    renderLine();
    return cleanup;
  }, [line]);

  return (
    <svg
      data-snapline-type="connector-line"
      height="4"
      ref={lineDomRef}
      style={lineState.style}
      width="4"
    >
      <path
        className="sl-connector-line"
        d={`M 0,0 C ${lineState.x1}, ${lineState.y1} ${lineState.x2}, ${lineState.y2} ${lineState.x3}, ${lineState.y3}`}
        markerEnd={`url(#arrow-${line.id})`}
        style={{
          fill: "none",
          stroke: "#545454",
          strokeLinecap: "round",
          strokeLinejoin: "round",
          strokeWidth: 4,
        }}
      />
      <marker id={`arrow-${line.id}`} viewBox="0 0 24 24" refX="0" refY="12" orient="auto">
        <polygon points="4,4 20,12 4,22" fill="#545454" />
      </marker>
    </svg>
  );
}
