// demo/svelte/src/lib/Background.svelte
<script lang="ts">
    import { onMount, setContext, getContext } from "svelte";
    import { Background } from "../../../../src/index";
    import type { Engine } from "../../../../src/index";
    let background: HTMLDivElement | null = null;

    const engine:Engine = getContext("engine");
    let bg = new Background(engine.global, null);

    setContext("bg", bg);

    onMount(() => {         
        bg.element = background as HTMLElement;
    });
</script>


<div id="sl-background" bind:this={background}></div>   


<style lang="scss">
    #sl-background {
        background-color: #fff;
        background-image: radial-gradient(circle, #cccccc 2px, transparent 1px);
        user-select: none;
    }
</style>

// demo/react/src/lib/Background.tsx
import { useContext, useRef, useEffect, createContext } from "react";
import { Background } from "../../../../src/index";
import { EngineContext } from "./Canvas";

export const BackgroundContext = createContext<Background | null>(null);

export default function BackgroundReact() {
  const engine = useContext(EngineContext);
  const backgroundElement = useRef<HTMLDivElement>(null);
  const backgroundRef = useRef<Background | null>(null);

  useEffect(() => {
    if (!engine) {
      console.warn("Background: No engine found in context");
      return;
    }

    backgroundRef.current = new Background(engine.global, null);

    if (backgroundElement.current) {
      backgroundRef.current.element = backgroundElement.current;
    }
  }, [engine]);

  useEffect(() => {
    if (backgroundRef.current && backgroundElement.current) {
      backgroundRef.current.element = backgroundElement.current;
    }
  }, []);

  return (
    <BackgroundContext.Provider value={backgroundRef.current}>
      <div
        id="sl-background"
        ref={backgroundElement}
        style={{
          backgroundColor: "#ffffff",
          backgroundImage:
            "radial-gradient(circle, #cccccc 2px, transparent 1px)",
          userSelect: "none",
        }}
      />
    </BackgroundContext.Provider>
  );
}
