// demo/svelte/src/lib/Canvas.svelte
<script lang="ts">
  import { onMount, setContext } from "svelte";
  import { getEngine } from "./engine.svelte";
  import type { Engine } from "../../../../src/index";

  let {
    id,
    children,
    engine = $bindable<Engine | null>(null),
  }: {
    id: string;
    style?: Record<string, string>;
    children: any;
    engine?: Engine | null;
  } = $props();
  let canvas: HTMLDivElement | null = null;

  const resolvedEngine = (engine ?? getEngine(id)) as Engine;
  engine = resolvedEngine;
  setContext("engine", resolvedEngine);

  resolvedEngine.enableCollisionEngine();

  onMount(() => {
    resolvedEngine.assignDom(canvas as HTMLElement);
    resolvedEngine.camera?.setCameraPosition(0, 0);
  });

  export function enableDebug() {
    resolvedEngine.enableDebug();
  }

  export function disableDebug() {
    resolvedEngine.disableDebug();
  }
</script>

<div
  id="snap-canvas"
  bind:this={canvas}
  style="height: 100%; overflow: hidden; position: relative;"
>
  {@render children()}
</div>

<style lang="scss">
</style>

// demo/react/src/lib/Canvas.tsx
import { Engine } from "../../../../src/index";
import { useRef } from "react";
import { useEffect } from "react";
import { createContext } from "react";

export const EngineContext = createContext<Engine | null>(null);

export default function SnapEngineReact({
  children,
}: {
  children: React.ReactNode;
}) {
  const engine = useRef(new Engine());
  const canvas = useRef<HTMLDivElement>(null); // canvas that contains the nodes

  useEffect(() => {
    if (!engine.current || !canvas.current) {
      return;
    }
    engine.current.assignDom(canvas.current as HTMLElement);
    engine.current.enableDebug();
  }, []);

  return (
    <div
      ref={canvas}
      style={{
        width: "100%",
        height: "100%",
        overflow: "hidden",
        position: "relative",
      }}
      id="snap-canvas"
    >
      <EngineContext.Provider value={engine.current}>
        {children}
      </EngineContext.Provider>
    </div>
  );
}
