// assets/snapsort/react/src/Ghost.tsx
import {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
} from "react";
import type { GhostInsertEvent } from "@snap-engine/snapsort";

export interface GhostProps extends HTMLAttributes<HTMLDivElement> {
  event: GhostInsertEvent;
}

export const Ghost = forwardRef<HTMLDivElement, GhostProps>(function Ghost(
  { children, className = "", event, id = "spacer", style, ...divProps },
  ref,
) {
  const elementRef = useRef<HTMLDivElement>(null);
  const original = event.original.dragSnapshot?.box ?? event.original.currentDomProperty;
  const ghostItem = event.ghostItem;
  const width = event.ghostRect?.width ?? original.width;
  const height = event.ghostRect?.height ?? original.height;

  useImperativeHandle(ref, () => elementRef.current as HTMLDivElement, []);

  const bindGhostElement = useCallback(
    (element: HTMLDivElement | null) => {
      elementRef.current = element;
      if (element) {
        ghostItem.element = element;
      } else if (ghostItem.element) {
        ghostItem.destroyDom(false);
      }
    },
    [ghostItem],
  );

  return (
    <div
      {...divProps}
      id={id}
      className={className}
      data-snapsort-ghost-entry={event.kind}
      ref={bindGhostElement}
      style={{
        boxSizing: "border-box",
        height,
        margin: `${original.margin.top}px ${original.margin.right}px ${original.margin.bottom}px ${original.margin.left}px`,
        width,
        ...style,
      }}
    >
      {children}
    </div>
  );
});

// assets/snapsort/svelte/src/Ghost.svelte
<script lang="ts">
  import type { GhostInsertEvent } from "@snap-engine/snapsort";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type GhostProps = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    event: GhostInsertEvent;
    children?: Snippet;
    className?: string;
  };

  let {
    event,
    children,
    class: classValue = "",
    className = "",
    style = "",
    id = "spacer",
    ...divProps
  }: GhostProps = $props();

  const footprintStyle = $derived.by(() => {
    const origProp = event.original.dragSnapshot?.box ?? event.original.currentDomProperty;
    const width = event.ghostRect?.width ?? origProp.width;
    const height = event.ghostRect?.height ?? origProp.height;
    return (
      `width:${width}px;height:${height}px;` +
      `margin:${origProp.margin.top}px ${origProp.margin.right}px ${origProp.margin.bottom}px ${origProp.margin.left}px;` +
      "box-sizing:border-box;"
    );
  });
  const mergedStyle = $derived(`${footprintStyle}${style}`);
  const mergedClass = $derived(`${classValue} ${className}`.trim());

  function bindGhostElement(node: HTMLElement) {
    event.ghostItem.element = node;
    return {
      destroy() {
        if (event.ghostItem.element === node) {
          event.ghostItem.destroyDom(false);
        }
      },
    };
  }
</script>

<div
  {...divProps}
  {id}
  class={mergedClass || undefined}
  data-snapsort-ghost-entry={event.kind}
  style={mergedStyle}
  use:bindGhostElement
>
  {@render children?.()}
</div>
