// assets/snapsort/react/src/Handle.tsx
import {
  forwardRef,
  useContext,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
  type ReactNode,
} from "react";
import { ItemObjectContext } from "./Item";

export interface HandleProps {
  children: ReactNode;
  className?: string;
  style?: CSSProperties;
}

export const Handle = forwardRef<HTMLDivElement, HandleProps>(function Handle(
  { children, className = "", style },
  ref,
) {
  const item = useContext(ItemObjectContext);
  const handleRef = useRef<HTMLDivElement>(null);

  useImperativeHandle(ref, () => handleRef.current as HTMLDivElement, []);

  useEffect(() => {
    const handleElement = handleRef.current;
    if (!item || !handleElement) return;

    item.addInputAlias(handleElement);
    return () => {
      item.removeInputAlias(handleElement);
    };
  }, [item]);

  return (
    <div
      ref={handleRef}
      className={`snapsort-handle ${className}`.trim()}
      style={style}
    >
      {children}
    </div>
  );
});

// assets/snapsort/svelte/src/Handle.svelte
<script lang="ts">
  import { getContext, onDestroy, onMount } from "svelte";
  import type {
    Item,
  } from "@snap-engine/snapsort";

  let {
    children,
    style = "",
    className = "",
  }: {
    children: any;
    style?: string;
    className?: string;
  } = $props();

  const itemObject: Item | null = getContext("item");
  let handleElement: HTMLElement | null = null;

  onMount(() => {
    if (itemObject && handleElement) {
      itemObject?.addInputAlias(handleElement);
    }
  });

  onDestroy(() => {
    if (itemObject && handleElement) {
      itemObject?.removeInputAlias(handleElement);
    }
  });
</script>

<div
  class="snapsort-handle {className}"
  bind:this={handleElement}
  {style}
>
  {@render children()}
</div>

<style>

</style>
