// assets/snapsort/react/src/Item.tsx
import {
  createContext,
  forwardRef,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useRef,
  type HTMLAttributes,
  type ReactNode,
} from "react";
import {
  Item as ItemObject,
  type ItemSnapshotMetadata,
} from "@snap-engine/snapsort";
import { useSnapSortEngine } from "./Engine";
import { ContainerObjectContext } from "./Container";

export const ItemObjectContext = createContext<ItemObject | null>(null);

export interface ItemProps
  extends Omit<HTMLAttributes<HTMLDivElement>, "children"> {
  children: ReactNode;
  className?: string;
  itemId?: string;
  itemObject?: ItemObject | null;
  metadata?: ItemSnapshotMetadata;
  /** Consumer-owned selection flag — see `Item.selected` in `@snap-engine/snapsort`. */
  selected?: boolean;
}

export const Item = forwardRef<ItemObject, ItemProps>(function SnapSortItem(
  { children, className = "", itemId, itemObject = null, metadata = {}, selected = false, style, ...divProps },
  ref,
) {
  const engine = useSnapSortEngine();
  const container = useContext(ContainerObjectContext);
  const itemDomRef = useRef<HTMLDivElement>(null);
  const ownsItemRef = useRef(itemObject == null);
  const itemRef = useRef<ItemObject | null>(itemObject);
  if (!itemRef.current) {
    itemRef.current = new ItemObject(engine, null);
  }
  const item = itemRef.current;
  const resolvedItemId =
    itemId ?? (typeof metadata.itemId === "string" ? metadata.itemId : undefined);
  if (resolvedItemId !== undefined) {
    item.itemId = resolvedItemId;
  }
  item.metadata = metadata;
  item.selected = selected;

  useImperativeHandle(ref, () => item, [item]);

  const setItemElement = useCallback(
    (element: HTMLDivElement | null) => {
      itemDomRef.current = element;
      if (element) {
        item.element = element;
      }
    },
    [item],
  );

  useEffect(() => {
    if (container && item.parent !== container) {
      container.addItem(item);
    }
    return () => {
      if (ownsItemRef.current) {
        item.destroy();
      }
    };
  }, [container, item]);

  return (
    <ItemObjectContext.Provider value={item}>
      <div
        {...divProps}
        ref={setItemElement}
        className={`snapsort-item ${className}`.trim()}
        style={{
          alignItems: "center",
          boxSizing: "border-box",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: 4,
          ...style,
        }}
      >
        {children}
      </div>
    </ItemObjectContext.Provider>
  );
});

// assets/snapsort/svelte/src/Item.svelte
<script lang="ts">
  import { getContext, setContext, onDestroy, untrack } from "svelte";
  import { Item as SnapSortItem } from "@snap-engine/snapsort";
  import type {
    Container,
    ItemSnapshotMetadata,
  } from "@snap-engine/snapsort";
  import type { Engine } from "@snap-engine/core";
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  type ItemProps = Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    children: Snippet;
    className?: string;
    itemId?: string;
    metadata?: ItemSnapshotMetadata;
    selected?: boolean;
    itemObject?: SnapSortItem | null;
  };

  let {
    children,
    itemId,
    style = "",
    class: classValue = "",
    className = "",
    metadata = {},
    selected = false,
    itemObject: providedItemObject = null,
    ...divProps
  }: ItemProps = $props();

  const engine: Engine = getContext("engine");
  const container: Container | null = getContext("container");
  const initial = untrack(() => ({ itemId, metadata, providedItemObject }));
  const ownsItem = initial.providedItemObject == null;
  const itemObject: SnapSortItem = initial.providedItemObject ?? new SnapSortItem(engine, container);
  const mergedClass = $derived(`snapsort-item ${classValue} ${className}`.trim());

  if ("itemId" in initial.metadata) {
    throw new Error("SnapSort Item: `metadata.itemId` was removed. Pass `itemId` as its own prop instead.");
  }

  if ("itemId" in metadata) {
    throw new Error("SnapSort Item: `metadata.itemId` was removed. Pass `itemId` as its own prop instead.");
  }

  setContext("item", itemObject);

  if (initial.itemId !== undefined) {
    itemObject.itemId = initial.itemId;
  }
  if (!itemObject.itemId) {
    throw new Error("SnapSort Item: missing required `itemId` prop.");
  }

  if (ownsItem || Object.keys(initial.metadata).length > 0) {
    itemObject.metadata = initial.metadata;
  }

  $effect(() => {
    if (itemId !== undefined) {
      itemObject.itemId = itemId;
    }
    itemObject.selected = selected;
  });

  onDestroy(() => {
    if (ownsItem) {
      itemObject.destroy();
    }
  });
</script>

<div
  {...divProps}
  class={mergedClass}
  bind:this={itemObject.element}
  {style}
>
  {@render children()}
</div>

<style>
  .snapsort-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: var(--size-4);
    box-sizing: border-box;
  }
</style>
