// assets/snapline/react/src/Node.tsx
import {
  createContext,
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type ComponentType,
  type CSSProperties,
  type ReactNode,
} from "react";
import { LineComponent, NodeComponent } from "@snap-engine/snapline";
import { useSnapLineEngine } from "./Engine";
import { Line } from "./Line";

export const NodeObjectContext = createContext<NodeComponent | null>(null);

export interface NodeProps {
  children: ReactNode;
  className?: string;
  lineComponent?: ComponentType<{ line: LineComponent }>;
  nodeObject?: NodeComponent | null;
  style?: CSSProperties;
  x?: number;
  y?: number;
}

export const Node = forwardRef<NodeComponent, NodeProps>(function Node(
  {
    children,
    className = "",
    lineComponent: LineRenderer = Line,
    nodeObject = null,
    style,
    x = 0,
    y = 0,
  },
  ref,
) {
  const engine = useSnapLineEngine();
  const nodeDomRef = useRef<HTMLDivElement>(null);
  const ownsNodeRef = useRef(nodeObject == null);
  const nodeRef = useRef<NodeComponent | null>(nodeObject);
  if (!nodeRef.current) {
    nodeRef.current = new NodeComponent(engine, null);
  }
  const node = nodeRef.current;
  const [lineList, setLineList] = useState<LineComponent[]>(
    node.getAllOutgoingLines(),
  );

  useImperativeHandle(ref, () => node, [node]);

  useEffect(() => {
    node.worldTransform = { x, y };
    if (nodeDomRef.current) {
      node.element = nodeDomRef.current;
      node.writeTransform();
    }
    node.setLineListCallback((lines: LineComponent[]) => {
      setLineList([...lines]);
    });
    setLineList([...node.getAllOutgoingLines()]);

    return () => {
      node.setLineListCallback(() => {});
      if (ownsNodeRef.current) {
        node.destroy();
      }
    };
  }, [node, x, y]);

  return (
    <NodeObjectContext.Provider value={node}>
      {lineList.map((line) => (
        <LineRenderer key={line.id} line={line} />
      ))}
      <div
        ref={nodeDomRef}
        data-snapline-type="node"
        className={className}
        style={{
          position: "absolute",
          ...style,
        }}
      >
        {children}
      </div>
    </NodeObjectContext.Provider>
  );
});

// assets/snapline/svelte/src/Node.svelte
<script lang="ts">
    import { NodeComponent, LineComponent } from "@snap-engine/snapline";
    import type { Engine } from "@snap-engine/core";
    import Line from "./Line.svelte";
    import { onMount, setContext, getContext, onDestroy } from "svelte";
    import { blur } from "svelte/transition";

    let { className = "", LineSvelteComponent = Line, nodeObject = null, x = 0, y = 0, children}: {
        className?: string,
        LineSvelteComponent?: typeof Line,
        nodeObject?: NodeComponent | null,
        x?: number,
        y?: number,
        children: any
    } = $props();
    let nodeDOM: HTMLDivElement | null = null;
    let engine: Engine = getContext("engine");
    const ownsNode = nodeObject == null;
    if (!nodeObject) {
         nodeObject = new NodeComponent(engine, null);
    }
    let lineList: LineComponent[] = $state(nodeObject.getAllOutgoingLines());

    setContext("nodeObject", nodeObject);

    onMount(() => {
        nodeObject.worldTransform = { x, y };
        nodeObject.element = nodeDOM as HTMLElement;
        nodeObject.writeTransform();
        nodeObject.setLineListCallback((lines: LineComponent[]) => {
            lineList = lines;
        });
        lineList = nodeObject.getAllOutgoingLines();
    });

    onDestroy(() => {
        nodeObject.setLineListCallback(() => {});
        if (ownsNode) {
            nodeObject.destroy();
        }
    });

    export function addSetPropCallback(name: string, callback: (prop: any) => void) {
        nodeObject!.addSetPropCallback(callback, name);
    }

    export function getNodeObject() {
        return nodeObject;
    }

</script>


{#each lineList as line (line.id)}
    <LineSvelteComponent {line} />
{/each}
<div bind:this={nodeDOM} data-snapline-type="node" class={className} style="position: absolute;" transition:blur|global={{duration: 200}}>
    {@render children()}
</div>


<style>

</style>
