// demo/react/src/lib/node_ui/Select.tsx
import { useContext, useEffect, useRef } from "react";
import { RectSelectComponent } from "../../../../../src/index";
import { EngineContext } from "../Canvas";

export default function SelectReact() {
  const engine = useContext(EngineContext);
  const selectDOM = useRef<HTMLDivElement>(null);
  const selectRef = useRef<RectSelectComponent | null>(null);

  useEffect(() => {
    if (!engine) {
      console.warn("Select: No engine found in context");
      return;
    }

    selectRef.current = new RectSelectComponent(engine, null);

    if (selectDOM.current) {
      selectRef.current.element = selectDOM.current;
    }

    return () => {
      // Cleanup if needed
      selectRef.current = null;
    };
  }, [engine]);

  return (
    <div
      id="select-container"
      ref={selectDOM}
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        width: 0,
        height: 0,
        backgroundColor: "rgba(0, 0, 0, 0.103)",
      }}
    />
  );
}

// assets/snapline/svelte/src/Select.svelte

<script lang="ts">
    import { RectSelectComponent } from "@snapline/core";
    import type { Engine } from "snap-engine";
    import { onMount, getContext } from "svelte";

    let selectDOM: HTMLDivElement | null = null;
    let engine: Engine = getContext("engine");
    let select = new RectSelectComponent(engine, null);

    onMount(() => {
        select.element = selectDOM as HTMLElement;
    });

</script>

<div id="select-container" bind:this={selectDOM}></div>

<style>
    #select-container {
        position: absolute;
        top: 0;
        left: 0;
        width: 0;
        height: 0;
        background-color: rgba(0, 0, 0, 0.103);
    }
</style>
